### ISSUE TITLE
License Check CI fails for non-maintainers

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently if a non-maintainer (such as dependabot) makes a PR the license check CI will fail in the following manner:

```
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v4.1/dist/index.js:4480:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HttpError',
  status: 403,
  response: {
    url: 'https://api.github.com/repos/Kong/kubernetes-ingress-controller/issues/1883/labels',
    status: 403,
```

### Expected 

All contributions should be able to have the licensing checked via CI.

**Comment by shaneutt** [comment]
We recently fixed this, for contributors not part of the Kong org the license check CI will not try and pull secrets any longer.
