### ISSUE TITLE
error: invalid memory address or nil pointer dereference, reports.go:73

### ISSUE THREAD

**Issue by huang-cn** [Kong/kubernetes-ingress-controller#2591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

deploy Kong gateway in OCP cluster,  gatewat-kong pod Crashloopbackoff, ingress-controller container log report error.    

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x13586b8]

goroutine 988 [running]:
github.com/kong/kubernetes-ingress-controller/internal/util.Reporter.Run({{{0xc00097e150, 0xf}, {0xc000c10670, 0x5}, {0x17b87de, 0x7}, {0xc0006b45a0, 0x1d}, {0xc00040c718, 0x3}, ...}, ...}, ...)
      /workspace/internal/util/reports.go:69 +0x178
created by github.com/kong/kubernetes-ingress-controller/internal/mgrutils.RunReport
      /workspace/internal/mgrutils/reports.go:73 +0x4de
```

### Expected Behavior

ingress-controller container should be started and ready.

### Kong Ingress Controller version

```shell
2.0.0
```

### Kubernetes version

```shell
OCP Server: 4.8.39
Kubernetes Version: v1.21.8+ed4d8fd
```

### Anything else?

tried delete gateway-kong pod the problem persist.

**Comment by pmalek** [comment]
Hi @huang-cn 

Thanks for reporting this. It seems that the issue you're describing has been fixed in [v2.0.4](https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v2.0.4) in this PR: https://github.com/Kong/kubernetes-ingress-controller/pull/1961

Please try updating to v2.0.4 (or any newer version) and let us know if it fixes your issue.

**Comment by pmalek** [comment]
It might be the case given the context where the error happens. Not sure though haven't seen the error myself 🙃

**Comment by huang-cn** [comment]
@pmalek Thansk for the help!  
closing this issue.
