### ISSUE TITLE
Nightly integration tests failing - GKE & Kubernetes v1.21.0 (test-previous-kubernetes-gke) 

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#2958]
Integration tests in the nightly workflow (test-previous-kubernetes-gke) are failing due to the following error: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x234ceb2]

goroutine 1491 [running]:
github.com/kong/kubernetes-ingress-controller/v2/internal/store.Store.GetIngressClassParametersV1Alpha1(***0x32a9c58, 0xc000c343d8***, ***0x32a9c58, 0xc000c343f0***, ***0x32a9c58, 0xc000c34408***, ***0x32a9c58, 0xc000c34420***, ***0x32a9c58, 0xc000c34438***, ...***, ...***)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/store/store.go:868 +0x1b2
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane/parser.getIngressClassParametersOrDefault(...)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/parser/parser.go:679
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane/parser.(*Parser).ingressRulesFromIngressV1beta1(0xc0005e1a98)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/parser/translate_ingress.go:24 +0x9a
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane/parser.(*Parser).Build(0xc0005e1a98)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/parser/parser.go:72 +0x36
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane.(*KongClient).Update(0xc000c60180, ***0x329ce60, 0xc000a23440***)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/kong_client.go:314 +0x385
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane.(*Synchronizer).startUpdateServer(0xc000b375c0, ***0x329ce60, 0xc000a23440***)
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/synchronizer.go:162 +0xdd
created by github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane.(*Synchronizer).Start
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/dataplane/synchronizer.go:100 +0x14a
FAIL	github.com/kong/kubernetes-ingress-controller/v2/test/integration	435.831s
```

Sample run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3102816618/jobs/5025633520#step:5:674

It's probably caused by dereferencing `ingressClass.Spec.Parameters.Namespace` which is optional when `ingressClass.Spec.Parameters.Scope` is not set to `Namespace`: https://github.com/Kong/kubernetes-ingress-controller/blob/94969ef3dbb82695edc787cb6c69be41de7bdd30/internal/store/store.go#L868

**Comment by randmonkey** [comment]
The reason why the test panics is: the `IngressClass` has a non-nil `Spec.Parameters` but `Spec.Parameters.Namespace` is `nil`.    From the reference of `IngressClass` API: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-class-v1/, the `IngressClass` is intended to use a cluster wide parameter (which is the default configuration). But our `IngressClassParameters` is namespaced, and the `GetIngressClassParametersV1Alpha1` did not consider the situation where `ingressClass` used a cluster wide parameter. 

Because it makes KIC panic, I would consider this issue as high priority and would consider make a patch release.
