### ISSUE TITLE
Knative related integration tests fails

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3965]
Recent PRs fails on workflows `integration/dbless-knative` and `integration/postgres-knative`, which runs integration test cases related to knative. We need to fix the integration tests.

Related CI run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4913118855/jobs/8773586338?pr=3964

```
time="2023-05-08T08:38:06Z" level=debug msg="no configuration change; resource status update not necessary, skipping"
    knative_test.go:146: error getting knative ingress: ingresses.networking.internal.knative.dev "helloworld-go" not found
    knative_test.go:143: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/knative_test.go:143
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/knative_test.go:102
        	Error:      	Condition never satisfied
        	Test:       	TestKnativeIngress
        	Messages:   	true
    knative_test.go:201: expected HTTP 200 but got 404, with body: "{\n  \"message\":\"no Route matched with those values\"\n}"
```

```
    knative_test.go:201: expected HTTP 200 but got 404, with body: "{\n  \"message\":\"no Route matched with those values\"\n}"
    knative_test.go:180: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/knative_test.go:180
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/knative_test.go:102
        	Error:      	Condition never satisfied
        	Test:       	TestKnativeIngress
    knative_test.go:102: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/knative_test.go:102
        	Error:      	Should be true
        	Test:       	TestKnativeIngress
        	Messages:   	true
    knative_test.go:97: cleaning up knative services used for testing
```

## Acceptance Criteria
- [ ] knative related integration tests passes

**Comment by programmer04** [comment]
For both `integration/dbless-knative` and `integration/postgres-knative` in execution logs

```
    knative_test.go:201: expected HTTP 200 but got 404, with body: "{\n  \"message\":\"no Route matched with those values\"\n}"
    knative_test.go:180: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/knative_test.go:180
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/knative_test.go:102
        	Error:      	Condition never satisfied
        	Test:       	TestKnativeIngress
    knative_test.go:102: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/knative_test.go:102
        	Error:      	Should be true
        	Test:       	TestKnativeIngress
        	Messages:   	true
    knative_test.go:97: cleaning up knative services used for testing
```
and at the end
```
ERROR: failed cleaning up the cluster: Delete "https://127.0.0.1:41565/apis/gateway.networking.k8s.io/v1beta1/gatewayclasses/kong-unmanaged": dial tcp 127.0.0.1:41565: connect: connection refused
FAIL	github.com/kong/kubernetes-ingress-controller/v2/test/integration	423.805s
```

**Comment by randmonkey** [comment]
I found the following output in the tests:
```
time="2023-05-08T17:18:26+08:00" level=error msg="kind must be registered to the Scheme" error="no kind is registered for the type v1alpha1.Ingress in scheme \"pkg/runtime/scheme.go:100\"" logger=controller-runtime.source
    knative_test.go:146: error getting knative ingress: ingresses.networking.internal.knative.dev "helloworld-go" not found

```
finally controller manager panicked with the following message
```
panic: failed to wait for Knativev1alpha1Ingress caches to sync: timed out waiting for cache to be synced
goroutine 1225 [running]:
github.com/kong/kubernetes-ingress-controller/v2/internal/util/test.DeployControllerManagerForCluster.func1()
	/home/runner/kong-repos/kubernetes-ingress-controller/internal/util/test/controller_manager.go:96 +0x2a5
created by github.com/kong/kubernetes-ingress-controller/v2/internal/util/test.DeployControllerManagerForCluster
	/home/runner/kong-repos/kubernetes-ingress-controller/internal/util/test/controller_manager.go:92 +0xbca
FAIL	github.com/kong/kubernetes-ingress-controller/v2/test/integration	338.654s
FAIL
make[1]: *** [Makefile:352: _test.integration] Error 1
make: *** [Makefile:369: test.integration.dbless.knative] Error 2
```
