### ISSUE TITLE
Flaky test: `TestGatewayWithGatewayClassReconciliation`

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4418]
```
=== FAIL: test/envtest  (0.00s)
panic: test timed out after 10m0s
running tests:
	TestGatewayWithGatewayClassReconciliation (9m19s)

goroutine 4872 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:2241 +0x219
created by time.goFunc
	/opt/hostedtoolcache/go/1.20.6/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 9 minutes]:
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1542 +0x8eb
testing.tRunner(0xc00030eb60, 0xc000171b40)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1582 +0x255
testing.runTests(0xc0001d0c80?, {0x44a2c40, 0x8, 0x8}, {0x1c?, 0x4ac9f9?, 0x44c0be0?})
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:2034 +0x87d
testing.(*M).Run(0xc0001d0c80)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1906 +0xb45
main.main()
	_testmain.go:92 +0x2fd

goroutine 446 [semacquire]:
sync.runtime_Semacquire(0xc000cf1928?)
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc000cf1920)
	/opt/hostedtoolcache/go/1.20.6/x64/src/sync/waitgroup.go:116 +0xa5
github.com/kong/kubernetes-ingress-controller/v2/test/envtest.Setup.func2()
	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/setup.go:104 +0xc5
testing.(*common).Cleanup.func1()
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1150 +0x194
testing.(*common).runCleanup(0xc000f45520, 0x1)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1328 +0x1ea
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1545 +0x936
testing.tRunner(0xc000f45520, 0x30ed190)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1582 +0x255
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1629 +0x806

goroutine 1496 [select]:
github.com/gammazero/workerpool.(*WorkerPool).dispatch(0xc000dea400)
	/home/runner/go/pkg/mod/github.com/gammazero/workerpool@v1.1.3/workerpool.go:185 +0x225
created by github.com/gammazero/workerpool.New
	/opt/hostedtoolcache/go/1.20.6/x64/src/syscall/syscall_linux.go:91 +0x45
os.(*Process).blockUntilWaitable(0xc000b27ad0)
	/opt/hostedtoolcache/go/1.20.6/x64/src/os/wait_waitid.go:32 +0x9f
os.(*Process).wait(0xc000b27ad0)
	/opt/hostedtoolcache/go/1.20.6/x64/src/os/exec_unix.go:22 +0x53
os.(*Process).Wait(...)
	/opt/hostedtoolcache/go/1.20.6/x64/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc00120e6e0)
	/opt/hostedtoolcache/go/1.20.6/x64/src/os/exec/exec.go:890 +0xc5
sigs.k8s.io/controller-runtime/pkg/internal/testing/process.(*State).Start.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/testing/process/process.go:174 +0xc5
created by sigs.k8s.io/controller-runtime/pkg/internal/testing/process.(*State).Start
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/testing/process/process.go:172 +0x6db
FAIL	github.com/kong/kubernetes-ingress-controller/v2/test/envtest	600.674s

=== FAIL: test/envtest TestGatewayWithGatewayClassReconciliation/unmanaged_gateway_class (553.81s)
    gatewayclass_envtest_test.go:327: deploying gateway 257ca6d4-a193-42cf-b1f6-8e15007f9619 using unmanaged-gateway-class gateway class
    gatewayclass_envtest_test.go:216: verifying that the Gateway 257ca6d4-a193-42cf-b1f6-8e15007f9619 does not get scheduled by the controller due to missing its GatewayClass
    gatewayclass_envtest_test.go:237: deploying gateway class unmanaged-gateway-class
    gatewayclass_envtest_test.go:241: now that the GatewayClass exists, verifying that the Gateway 257ca6d4-a193-42cf-b1f6-8e15007f9619 gets Accepted and Programmed
    gatewayclass_envtest_test.go:258: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/gatewayclass_envtest_test.go:258
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/gatewayclass_envtest_test.go:333
        	Error:      	Received unexpected error:
        	            	client rate limiter Wait returned an error: context deadline exceeded
        	Test:       	TestGatewayWithGatewayClassReconciliation/unmanaged_gateway_class
    controller.go:58: Test TestGatewayWithGatewayClassReconciliation/unmanaged_gateway_class failed: dumping controller logs
        time="2023-07-27T10:53:50Z" level=info msg="Starting EventSource" source="kind source: *v1beta1.Gateway"
        time="2023-07-27T10:53:50Z" level=info msg="Starting EventSource" source="kind source: *v1beta1.GatewayClass"
        time="2023-07-27T10:53:50Z" level=info msg="Starting EventSource" source="kind source: *v1.Service"
        time="2023-07-27T10:53:50Z" level=info msg="Starting EventSource" source="kind source: *v1beta1.HTTPRoute"
        time="2023-07-27T10:53:50Z" level=info msg="Starting EventSource" source="kind source: *v1beta1.ReferenceGrant"
        time="2023-07-27T10:53:50Z" level=info msg="Starting Controller"
        time="2023-07-27T10:53:50Z" level=info msg="Starting EventSource" logger=V1Beta1GatewayClass source="kind source: *v1beta1.GatewayClass"
        time="2023-07-27T10:53:50Z" level=info msg="Starting Controller" logger=V1Beta1GatewayClass
        time="2023-07-27T10:53:50Z" level=info msg="Starting workers" logger=V1Beta1GatewayClass worker count=1
        time="2023-07-27T10:53:50Z" level=info msg="Starting workers" worker count=1
        time="2023-07-27T10:53:52Z" level=error msg="could not retrieve gatewayclass" error="gatewayclasses.gateway.networking.k8s.io \"unmanaged-gateway-class\" not found" gatewayclass="\"unmanaged-gateway-class\""
        time="2023-07-27T10:53:52Z" level=error msg="Reconciler error" error="Operation cannot be fulfilled on gateways.gateway.networking.k8s.io \"257ca6d4-a193-42cf-b1f6-8e15007f9619\": the object has been modified; please apply your changes to the latest version and try again" reconcileID="\"e8a8aba8-b4b5-4495-85df-8049b50dbe33\""
        time="2023-07-27T10:53:52Z" level=error msg="could not determine service for gateway" GatewayV1Beta1Gateway="{\"Namespace\":\"63a44541-5a19-4208-916b-85bd6ee162d9\",\"Name\":\"257ca6d4-a193-42cf-b1f6-8e15007f9619\"}" error="service ref 22a3865c-6f80-4347-a869-b2d4d5b165f9/publish-svc did not match controller manager ref 63a44541-5a19-4208-916b-85bd6ee162d9/publish-svc or /" name=257ca6d4-a193-42cf-b1f6-8e15007f9619 namespace=63a44541-5a19-4208-916b-85bd6ee162d9
        time="2023-07-27T10:53:52Z" level=error msg="Reconciler error" error="service ref 22a3865c-6f80-4347-a869-b2d4d5b165f9/publish-svc did not match controller manager ref 63a44541-5a19-4208-916b-85bd6ee162d9/publish-svc or /" reconcileID="\"823f6328-ca8d-4629-b44b-54a732aad555\""
        time="2023-07-27T10:53:52Z" level=error msg="could not determine service for gateway" GatewayV1Beta1Gateway="{\"Namespace\":\"63a44541-5a19-4208-916b-85bd6ee162d9\",\"Name\":\"257ca6d4-a193-42cf-b1f6-8e15007f9619\"}" error="service ref 22a3865c-6f80-4347-a869-b2d4d5b165f9/publish-svc did not match controller manager ref 63a44541-5a19-4208-916b-85bd6ee162d9/publish-svc or /" name=257ca6d4-a193-42cf-b1f6-8e15007f9619 namespace=63a44541-5a19-4208-916b-85bd6ee162d9
        time="2023-07-27T10:53:52Z" level=error msg="Reconciler error" error="service ref 22a3865c-6f80-4347-a869-b2d4d5b165f9/publish-svc did not match controller manager ref 63a44541-5a19-4208-916b-85bd6ee162d9/publish-svc or /" reconcileID="\"b9716ef6-7e02-4c9f-9f96-d45c37067de8\""
```

Failed CI run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5679611421/job/15392099121

**Comment by pmalek** [comment]
This is still failing 😒 

https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6746633276/job/18340995074

```
      gatewayclass_envtest_test.go:368: deploying gateway 3c654eb9-4aed-4802-ae72-b130ac454575 using unmanaged-gateway-class gateway class
      gatewayclass_envtest_test.go:246: verifying that the Gateway 3c654eb9-4aed-4802-ae72-b130ac454575 does not get scheduled by the controller due to missing its GatewayClass
      gatewayclass_envtest_test.go:279: deploying gateway class unmanaged-gateway-class
      gatewayclass_envtest_test.go:283: now that the GatewayClass exists, verifying that the Gateway 3c654eb9-4aed-4802-ae72-b130ac454575 gets Accepted and Programmed
      gatewayclass_envtest_test.go:305: Gateway 3c654eb9-4aed-4802-ae72-b130ac454575 still doesn't have the Programmed condition with Status True
      gatewayclass_envtest_test.go:305: Gateway 3c654eb9-4aed-4802-ae72-b130ac454575 still doesn't have the Programmed condition with Status True
      gatewayclass_envtest_test.go:305: Gateway 3c654eb9-4aed-4802-ae72-b130ac454575 still doesn't have the Programmed condition with Status True
      gatewayclass_envtest_test.go:299: context got cancelled: context deadline exceeded
      controller.go:55: Test TestGatewayWithGatewayClassReconciliation/unmanaged_gateway_class failed: dumping controller logs
      controller.go:55: 2023-11-03T14:45:40Z	info	Starting EventSource	{"source": "kind source: *v1.Gateway"}
      controller.go:55: 2023-11-03T14:45:40Z	info	V1Beta1GatewayClass	Starting EventSource	{"source": "kind source: *v1.GatewayClass"}
      controller.go:55: 2023-11-03T14:45:40Z	info	Starting EventSource	{"source": "kind source: *v1.GatewayClass"}
      controller.go:55: 2023-11-03T14:45:40Z	info	V1Beta1GatewayClass	Starting Controller
      controller.go:55: 2023-11-03T14:45:40Z	info	Starting EventSource	{"source": "kind source: *v1.Service"}
      controller.go:55: 2023-11-03T14:45:40Z	info	Starting EventSource	{"source": "kind source: *v1.HTTPRoute"}
      controller.go:55: 2023-11-03T14:45:40Z	info	Starting EventSource	{"source": "kind source: *v1beta1.ReferenceGrant"}
      controller.go:55: 2023-11-03T14:45:40Z	info	Starting Controller
      controller.go:55: 2023-11-03T14:45:40Z	info	V1Beta1GatewayClass	Starting workers	{"worker count": 1}
      controller.go:55: 2023-11-03T14:45:40Z	error	Could not retrieve gatewayclass	{"gatewayclass": "unmanaged-gateway-class", "error": "gatewayclasses.gateway.networking.k8s.io \"unmanaged-gateway-class\" not found"}
      controller.go:55: 2023-11-03T14:45:40Z	info	Starting workers	{"worker count": 1}
      controller.go:55: 2023-11-03T14:45:40Z	error	Failed to retrieve gateway class in watch predicates	{"gatewayclass": "unmanaged-gateway-class", "error": "gatewayclasses.gateway.networking.k8s.io \"unmanaged-gateway-class\" not found"}
      controller.go:55: 2023-11-03T14:45:43Z	debug	V1Beta1GatewayClass	Processing gatewayclass	{"GatewayV1GatewayClass": {"name":"unmanaged-gateway-class"}, "name": "unmanaged-gateway-class"}
      controller.go:55: 2023-11-03T14:45:43Z	debug	Processing gateway	{"GatewayV1Gateway": {"name":"3c654eb9-4aed-4802-ae72-b130ac454575","namespace":"6b9008fe-ad53-467b-9a21-7e8eda9ad9b0"}, "namespace": "6b9008fe-ad53-467b-9a21-7e8eda9ad9b0", "name": "3c654eb9-4aed-4802-ae72-b130ac454575"}
```

**Comment by pmalek** [comment]
Does not show up in BuildPulse anymore: https://app.buildpulse.io/@Kong/kubernetes-ingress-controller?q=TestGatewayWithGatewayClassReconciliation&select%5B%5D=&show_type=default&sort=disruptiveness&daterange=September+1+-+December+31&starting_at=%222024-05-31T22%3A00%3A00.000Z%22&ending_at=%222024-12-31T22%3A59%3A59.999Z%22&user_time_zone=Europe%2FWarsaw

Closing.
