### ISSUE TITLE
When KIC 2.12 is deployed in cluster, it complains about missing call to `SetLogger()` when killed/shutdown

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deployed in cluster and killed, 2.12 yields the following log

```
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
    >  goroutine 58 [running]:
    >  runtime/debug.Stack()
    >      /usr/local/go/src/runtime/debug/stack.go:24 +0x64
    >  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
    >      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/log/log.go:60 +0xf4
    >  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0x4000787900, 0x4000b8c680?)
    >      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/log/deleg.go:111 +0x38
    >  github.com/go-logr/logr.Logger.Enabled(...)
    >      /go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:261
    >  github.com/go-logr/logr.Logger.Info({{0x1c50d28?, 0x4000787900?}, 0x4000868500?}, {0x19a2dfd, 0x35}, {0x0, 0x0, 0x0})
    >      /go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:274 +0x5c
    >  sigs.k8s.io/controller-runtime/pkg/metrics/server.(*defaultServer).Start.func1()
    >      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/metrics/server/server.go:231 +0x7c
    >  created by sigs.k8s.io/controller-runtime/pkg/metrics/server.(*defaultServer).Start in goroutine 56
    >      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/metrics/server/server.go:229 +0x6f8
```

### Expected Behavior

No stack traces are dumped when KIC's Pod is killed

### Steps To Reproduce

```markdown
1. Deploy 2.12 in cluster
1. Kill the pod
1. Observe the stack trace about missing call to `SetLogger()`
```

### Kong Ingress Controller version

```shell
2.12
```

### Kubernetes version

```shell
1.28
```

**Comment by programmer04** [comment]
I resolved it in the tests
- https://github.com/Kong/kubernetes-ingress-controller/pull/4661

I think a similar approach will work here too
