### ISSUE TITLE
KongConsumer without username crashes KIC

### ISSUE THREAD

**Issue by scottambroseio** [Kong/kubernetes-ingress-controller#550]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Hey all,

I've been running into an issue getting this controller up and running. I've managed to figure out what the cause seems to be and have managed to work around it, but I think this is a genuine bug.

```
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.7.0
  Build:      e4605db
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.13.1
-------------------------------------------------------------------------------

I0224 10:39:36.250499       1 main.go:407] Creating API client for https://100.64.0.1:443
I0224 10:39:36.256804       1 main.go:451] Running in Kubernetes Cluster version v1.15 (v1.15.6) - git (clean) commit 7015f71e75f670eb9e7ebd4b5749639d42e20079 - platform linux/amd64
I0224 10:39:36.267404       1 main.go:187] kong version: 1.4.3
I0224 10:39:36.267423       1 main.go:196] Kong datastore: off
I0224 10:39:36.582344       1 controller.go:224] starting Ingress controller
I0224 10:39:36.584853       1 status.go:201] new leader elected: kong-kong-74ddc87c5b-6v665
E0224 10:39:36.589789       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 180 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x142a5c0, 0x2229630)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x82
panic(0x142a5c0, 0x2229630)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).toDeckContent.func9(0x1, 0x0, 0x97)
        /kong-ingress-controller/internal/ingress/controller/kong.go:302 +0x47
sort.insertionSort_func(0xc002a999a8, 0xc002af5410, 0x0, 0x3)
        /usr/local/go/src/sort/zfuncversion.go:12 +0xb1
sort.stable_func(0xc002a999a8, 0xc002af5410, 0x3)
        /usr/local/go/src/sort/zfuncversion.go:171 +0x86
sort.SliceStable(0x137e3a0, 0xc002b106c0, 0xc002a999a8)
        /usr/local/go/src/sort/slice.go:27 +0xcb
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).toDeckContent(0xc0006e6000, 0xc001a52680, 0x0, 0x0, 0x0)
        /kong-ingress-controller/internal/ingress/controller/kong.go:301 +0x1272
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).OnUpdate(0xc0006e6000, 0xc001a52680, 0x0, 0x0)
        /kong-ingress-controller/internal/ingress/controller/kong.go:45 +0x4d
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).syncIngress(0xc0006e6000, 0x149a2a0, 0xc001a2df20, 0xc022c092c1, 0x8312ed838b1)
        /kong-ingress-controller/internal/ingress/controller/controller.go:117 +0x1fa
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).worker(0xc0007c0f60)
        /kong-ingress-controller/internal/ingress/task/queue.go:111 +0x2df
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00030b7a8)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002a9bfa8, 0x3b9aca00, 0x0, 0x1, 0xc0006504e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).Run(0xc0007c0f60, 0x3b9aca00, 0xc0006504e0)
        /kong-ingress-controller/internal/ingress/task/queue.go:59 +0x6b
created by github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).Start
        /kong-ingress-controller/internal/ingress/controller/controller.go:232 +0xe8
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11f3497]

goroutine 180 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x142a5c0, 0x2229630)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).toDeckContent.func9(0x1, 0x0, 0x97)
        /kong-ingress-controller/internal/ingress/controller/kong.go:302 +0x47
sort.insertionSort_func(0xc002a999a8, 0xc002af5410, 0x0, 0x3)
        /usr/local/go/src/sort/zfuncversion.go:12 +0xb1
sort.stable_func(0xc002a999a8, 0xc002af5410, 0x3)
        /usr/local/go/src/sort/zfuncversion.go:171 +0x86
sort.SliceStable(0x137e3a0, 0xc002b106c0, 0xc002a999a8)
        /usr/local/go/src/sort/slice.go:27 +0xcb
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).toDeckContent(0xc0006e6000, 0xc001a52680, 0x0, 0x0, 0x0)
        /kong-ingress-controller/internal/ingress/controller/kong.go:301 +0x1272
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).OnUpdate(0xc0006e6000, 0xc001a52680, 0x0, 0x0)
        /kong-ingress-controller/internal/ingress/controller/kong.go:45 +0x4d
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).syncIngress(0xc0006e6000, 0x149a2a0, 0xc001a2df20, 0xc022c092c1, 0x8312ed838b1)
        /kong-ingress-controller/internal/ingress/controller/controller.go:117 +0x1fa
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).worker(0xc0007c0f60)
        /kong-ingress-controller/internal/ingress/task/queue.go:111 +0x2df
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00030b7a8)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002a9bfa8, 0x3b9aca00, 0x0, 0x1, 0xc0006504e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).Run(0xc0007c0f60, 0x3b9aca00, 0xc0006504e0)
        /kong-ingress-controller/internal/ingress/task/queue.go:59 +0x6b
created by github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).Start
        /kong-ingress-controller/internal/ingress/controller/controller.go:232 +0xe8
```

The stack trace points to this LOC, which makes sense

https://github.com/Kong/kubernetes-ingress-controller/blob/master/internal/ingress/controller/kong.go#L302

`return strings.Compare(*content.Consumers[i].Username, *content.Consumers[j].Username) > 0`

I have some KongConsumers defined like follows

```yaml
apiVersion: configuration.konghq.com/v1
credentials:
- user-secret
custom_id: 123456
kind: KongConsumer
metadata:
  name: user
```

As you can see, I don't set the username property on the consumer as based on the docs, username is optional (either that or custom_id must be provided).

Version 1.2.0 of the kong/kong helm chart

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

### What happened

Kong pod fails to spin up as the ingress controller container crashes

### Expected behavior

The pod should spin up correctly

### Potential solution

Update the controller to it handles the case when KongConsumer objects don't have a username set

**Comment by hbagdi** [comment]
Currently, username is required for the custom resource KongConsumer. This will be relaxed in future but for now, it is required because of the underlying sync library that this controller uses.

I'm labeling this as a bug and we will update the code to handle it more gracefully.
If you use Admission webhook, then it _should_ deny the request if you do not supply a username.

If you want to use custom_id, then you can use `custom_id` and `username` as the same values. That's the only workaround that is possible as of today.

**Comment by ddides** [comment]
> If you want to use custom_id, then you can use custom_id and username as the same values. That's the only workaround that is possible as of today.

Is this still true? I'm having a similar issue on my current Kong deployment. If I create a new consumer the application immediately crashes with a similar looking stacktrace.

**Comment by ddides** [comment]
Okay, update. This absolutely _is_ still an issue on the latest release. That being said, I figured out the workaround and can add a few more details.

The big change I had to make is _all_ consumers need to have both a `username` and a `custom_id` specified. I had somehow created a few consumers without `username` fields and therefore was unable to create new consumers, even if I set both fields on the new consumers. I retroactively added usernames to the old consumers though and seem to be having no more issues.

```
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    1.0.0
  Build:      a34ce92
  Repository: git@github.com:Kong/kubernetes-ingress-controller.git
  Go:         go1.15.2
-------------------------------------------------------------------------------
```

**Comment by shaneutt** [comment]
Given the original stack trace I believe this issue could still affect `v2`, despite the re-architecture as it looks like it involves the usage of `deckgen` (which has stayed mostly the same) :thinking: 

I'll take a look at this for fixing in the upcoming `v2` release.

**Comment by zarelit** [comment]
@shaneutt is this going to be closed in favor of another issue for v2? It was mentioned the issue is still present

**Comment by shaneutt** [comment]
@zarelit this is fixed as per https://github.com/Kong/kubernetes-ingress-controller/pull/1658, which will be releasing in `v2.0.0` (about to move into beta). This is fixed by way of stopping the panic so that configurations are not interrupted, the changelog entry can be seen here: https://github.com/Kong/kubernetes-ingress-controller/blob/next/CHANGELOG.md#200-beta1---tbd

Let us know if this is helpful, or if you have any lingering questions and concerns we can address for you. :vulcan_salute:
