### ISSUE TITLE
Panic in 

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#6775]
### Problem statement

Recently, running KIC locally I stumbled across this `panic` when running with `FallbackConfiguration=true` feature flag:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102645e44]

goroutine 650 [running]:
github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane/fallback.DefaultCacheGraphProvider.CacheToGraph({}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
	/Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/internal/dataplane/fallback/cache_to_graph.go:27 +0xb4
github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane/fallback.(*Generator).GenerateExcludingBrokenObjects(_, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/internal/dataplane/fallback/fallback.go:37 +0xd8
github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane.(*KongClient).generateFallbackCache(_, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/internal/dataplane/kong_client.go:658 +0x4f8
github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane.(*KongClient).tryRecoveringWithFallbackConfiguration(_, {_, _}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/internal/dataplane/kong_client.go:602 +0xc0
github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane.(*KongClient).maybeTryRecoveringFromGatewaysSyncError(_, {_, _}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/internal/dataplane/kong_client.go:572 +0x174
github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane.(*KongClient).Update(0x140001e2400, {0x102fd67f0, 0x14001004d20})
	/Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/internal/dataplane/kong_client.go:503 +0xcfc
github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane.(*Synchronizer).startUpdateServer(0x1400016f7a0, {0x102fd67f0, 0x14001004d20})
	/Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/internal/dataplane/synchronizer.go:183 +0xfc
created by github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane.(*Synchronizer).Start in goroutine 201
	/Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/internal/dataplane/synchronizer.go:120 +0x394
```

### Acceptance criteria

- [ ] Using `FallbackConfiguration=true` feature flag does not cause `panic`s.

**Comment by pmalek** [comment]
Putting this tentatively in 3.4. If unfeasible, let's punt to 3.5.

**Comment by tao12345666333** [comment]
Are there any other additional configurations?

**Comment by lahabana** [comment]
@pmalek to update with a more detailed scenario to repro

**Comment by pmalek** [comment]
Added reproduction steps.

**Comment by randmonkey** [comment]
It looks like the `cacheSnapshot` was not initialized correctly in the `kongclient.Update`, so all the storages and `lock` are nils in the `cacheSnapshot`. 
We could try adding a check in `tryRecoveringWithFallbackConfiguration` to check if the `cacheSnapshot` was not initialized correctly and return a recovering error to tell that the recovery cannot be done because the snapshot cache was not built to prevent the panic. @pmalek WDYT for this workaround?

**Comment by pmalek** [comment]
That sounds sensible to me 👍
