### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by marandalucas** [Kong/kubernetes-ingress-controller#8]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
**BUG REPORT Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)**

**Kong Ingress controller version**:
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.0.1

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
Cloud provider or hardware configuration: AWS with Kops 1.8.6 + RBAC authorization

**What happened**:
```
kubectl logs -f kong-ingress-controller-74f498f5c8-ssfj9 -c ingress-controller
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.0.1
  Build:      git-bec2acd
  Repository: https://github.com/Kong/kubernetes-ingress-controller.git
-------------------------------------------------------------------------------

W0411 11:51:33.904666       7 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0411 11:51:33.904826       7 main.go:232] Creating API client for https://100.64.0.1:443
I0411 11:51:33.999124       7 main.go:276] Running in Kubernetes Cluster version v1.8 (v1.8.6) - git (clean) commit 6260bb08c46c31eea6cb538b34a9ceb3e406689c - platform linux/amd64
I0411 11:51:34.000552       7 main.go:97] validated kong/kong-proxy as the default backend
I0411 11:51:39.415448       7 main.go:162] kong version: 0.13.0
W0411 11:51:39.415479       7 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0411 11:51:39.415669       7 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0411 11:51:39.415791       7 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0411 11:51:39.420922       7 run.go:149] starting Ingress controller
I0411 11:51:40.623408       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"example", Name:"example-api-countries-svc", UID:"629d4368-3d74-11e8-9f2b-024882f23250", APIVersion:"extensions", ResourceVersion:"9315843", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress example/example-api-countries-svc
I0411 11:51:40.721868       7 store.go:544] running initial sync of secrets
I0411 11:51:40.721998       7 leaderelection.go:175] attempting to acquire leader lease  kong/ingress-controller-leader-nginx...
W0411 11:51:40.722150       7 controller.go:431] service example/example-api-countries-svc does not have any active endpoints
I0411 11:51:40.722178       7 controller.go:138] syncing Ingress configuration...
I0411 11:51:40.723654       7 status.go:196] new leader elected: kong-ingress-controller-6d599988b-xpl8j
W0411 11:51:40.829536       7 kong.go:263] service  does not exists in kong
I0411 11:51:40.831000       7 kong.go:270] service / does not contains any pluging. Checking if is required to remove plugins...
E0411 11:51:40.837659       7 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/aledbf/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:573
/home/aledbf/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502
/home/aledbf/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:63
/home/aledbf/.gimme/versions/go1.10.1.linux.amd64/src/runtime/signal_unix.go:388
/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/meta.go:159
/home/aledbf/go/src/github.com/kong/ingress-controller/internal/ingress/controller/kong.go:91
/home/aledbf/go/src/github.com/kong/ingress-controller/internal/ingress/controller/kong.go:91
/home/aledbf/go/src/github.com/kong/ingress-controller/internal/ingress/controller/controller.go:140
/home/aledbf/go/src/github.com/kong/ingress-controller/internal/ingress/controller/run.go:88
/home/aledbf/go/src/github.com/kong/ingress-controller/internal/task/queue.go:112
/home/aledbf/go/src/github.com/kong/ingress-controller/internal/task/queue.go:59
/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/aledbf/go/src/github.com/kong/ingress-controller/internal/task/queue.go:59
/home/aledbf/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10f4749]

goroutine 135 [running]:
github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x128cdc0, 0x1e28000)
	/home/aledbf/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).GetAnnotations(...)
	/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/meta.go:159
github.com/kong/ingress-controller/internal/ingress/controller.(*NGINXController).syncRoutes(0xc42010e000, 0xc4206b7800, 0x0, 0x0, 0x0)
	/home/aledbf/go/src/github.com/kong/ingress-controller/internal/ingress/controller/kong.go:592 +0xf09
github.com/kong/ingress-controller/internal/ingress/controller.(*NGINXController).OnUpdate(0xc42010e000, 0xc4206b7800, 0x0, 0x0)
	/home/aledbf/go/src/github.com/kong/ingress-controller/internal/ingress/controller/kong.go:91 +0x221
github.com/kong/ingress-controller/internal/ingress/controller.(*NGINXController).syncIngress(0xc42010e000, 0x12f3640, 0xc420444320, 0xc42b0a3ea4, 0x1992bad2d)
	/home/aledbf/go/src/github.com/kong/ingress-controller/internal/ingress/controller/controller.go:140 +0x2f2
github.com/kong/ingress-controller/internal/ingress/controller.(*NGINXController).(github.com/kong/ingress-controller/internal/ingress/controller.syncIngress)-fm(0x12f3640, 0xc420444320, 0xa, 0xc4204b1d68)
	/home/aledbf/go/src/github.com/kong/ingress-controller/internal/ingress/controller/run.go:88 +0x3e
github.com/kong/ingress-controller/internal/task.(*Queue).worker(0xc4203d4240)
	/home/aledbf/go/src/github.com/kong/ingress-controller/internal/task/queue.go:112 +0x34a
github.com/kong/ingress-controller/internal/task.(*Queue).(github.com/kong/ingress-controller/internal/task.worker)-fm()
	/home/aledbf/go/src/github.com/kong/ingress-controller/internal/task/queue.go:59 +0x2a
github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42001d7a8)
	/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420229fa8, 0x3b9aca00, 0x0, 0x1, 0xc420044420)
	/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42001d7a8, 0x3b9aca00, 0xc420044420)
	/home/aledbf/go/src/github.com/kong/ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kong/ingress-controller/internal/task.(*Queue).Run(0xc4203d4240, 0x3b9aca00, 0xc420044420)
	/home/aledbf/go/src/github.com/kong/ingress-controller/internal/task/queue.go:59 +0x55
created by github.com/kong/ingress-controller/internal/ingress/controller.(*NGINXController).Start
	/home/aledbf/go/src/github.com/kong/ingress-controller/internal/ingress/controller/run.go:157 +0xec

```
**What you expected to happen**:
Not memory error.

**How to reproduce it** (as minimally and precisely as possible):
When we add one ingress resource, after this the service show this error. 
Now can't start correctly, we configure the next resources and more and the error is the same.
```
  resources:
     limits:
      cpu: 100m
      memory: 356Mi
```

**Anything else we need to know**:

**Comment by aledbf** [comment]
@marandalucas please update the image to `quay.io/aledbf/kong-ingress-controller:dev`

**Comment by marandalucas** [comment]
thank you for your quick response.
I will update my code and will write you again.

**Comment by marandalucas** [comment]
we update the changes and see the following errors: **Failed to list *v1.KongIngress:**

```
$ kubectl get CustomResourceDefinition
NAME                                       AGE
kongconsumers.configuration.konghq.com     16m
kongcredentials.configuration.konghq.com   16m
kongingresses.configuration.konghq.com     10m
kongplugins.configuration.konghq.com       16m
```

```
$ kubectl describe CustomResourceDefinition kongingresses.configuration.konghq.com
Name:         kongingresses.configuration.konghq.com
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2018-04-11T13:40:31Z
  Generation:          1
  Resource Version:    9335256
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/kongingresses.configuration.konghq.com
  UID:                 e758d18a-3d8d-11e8-9f2b-024882f23250
Spec:
  Group:  configuration.konghq.com
  Names:
    Kind:       KongIngress
    List Kind:  KongIngressList
    Plural:     kongingresses
    Singular:   kongingress
  Scope:        Namespaced
  Version:      v1
Status:
  Accepted Names:
    Kind:       KongIngress
    List Kind:  KongIngressList
    Plural:     kongingresses
    Singular:   kongingress
  Conditions:
    Last Transition Time:  <nil>
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2018-04-11T13:40:31Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
Events:                    <none>
```

```
kubectl logs -f kong-ingress-controller-86bd548dcf-vpmpd -c ingress-controller
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.0.1
  Build:      git-a6168a0
  Repository: https://github.com/Kong/kubernetes-ingress-controller.git
-------------------------------------------------------------------------------

W0411 13:43:43.034121       7 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0411 13:43:43.034355       7 main.go:213] Creating API client for https://100.64.0.1:443
I0411 13:43:43.044130       7 main.go:257] Running in Kubernetes Cluster version v1.8 (v1.8.6) - git (clean) commit 6260bb08c46c31eea6cb538b34a9ceb3e406689c - platform linux/amd64
I0411 13:43:43.047440       7 main.go:94] validated coreplatform/kong-proxy as the default backend
I0411 13:43:44.128856       7 main.go:160] kong version: 0.13.0
I0411 13:43:44.526279       7 run.go:147] starting Ingress controller
E0411 13:43:44.529856       7 reflector.go:205] github.com/kong/kubernetes-ingress-controller/internal/ingress/controller/store/store.go:162: Failed to list *v1.KongIngress: kongingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:coreplatform:kong-serviceaccount" cannot list kongingresses.configuration.konghq.com at the cluster scope
E0411 13:43:45.532000       7 reflector.go:205] github.com/kong/kubernetes-ingress-controller/internal/ingress/controller/store/store.go:162: Failed to list *v1.KongIngress: kongingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:coreplatform:kong-serviceaccount" cannot list kongingresses.configuration.konghq.com at the cluster scope
E0411 13:43:46.534020       7 reflector.go:205] github.com/kong/kubernetes-ingress-controller/internal/ingress/controller/store/store.go:162: Failed to list *v1.KongIngress: kongingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:coreplatform:kong-serviceaccount" cannot list kongingresses.configuration.konghq.com at the cluster scope
E0411 13:43:47.535951       7 reflector.go:205] github.com/kong/kubernetes-ingress-controller/internal/ingress/controller/store/store.go:162: Failed to list *v1.KongIngress: kongingresses.configuration.konghq.com is forbidden: User "system:serviceaccount:coreplatform:kong-serviceaccount" cannot list kongingresses.configuration.konghq.com at the cluster scope
```

**Comment by aledbf** [comment]
Please run 
```
curl https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/manifests/rbac.yaml | kubectl apply -f -
```
